/**
 * Recipe Generate — `/recipe/generate`. SSE 점진 응답 → 최종 RecipeDisplay·NutritionPanel.
 *
 * SSOT: 07-ROUTING §7.3.2, 06-UI-MAPPING §6.4.1~3, 08-STREAMING §8.3~8.5,
 *       baseline §A.4·§A.5·§C.5·§D.2.
 *
 * 책임:
 * - useRecipeGenerate 훅 결합 — SSE 호출·청크 분기·AbortController·폴백·에러 매핑은 훅 책임.
 * - 본 화면은 (1) URL params 수신, (2) 초기값 있으면 자동 1회 generate, (3) UI 분기,
 *   (4) 취소 버튼·다시 시도 버튼·에러 노출만 담당 (SRP).
 *
 * 불변식 (baseline §D.2):
 * - useTossUserId 미사용 — 공개 endpoint이며 헤더 미부착(AC2.6).
 * - href/useRouter/Link 0건 — useNavigation/Route.useParams.
 * - text 청크 delta 사용자 표시 0건 — 훅의 progressText는 컴포넌트에서 미참조(인디케이터만).
 * - GeneratedRecipe.id 참조 0건 (AC2.5).
 */

import React, { useCallback, useEffect, useRef } from 'react';
import { ScrollView, StyleSheet, View } from 'react-native';
import {
  Button,
  PageNavbar,
  Txt,
} from '@toss/tds-react-native';
import { createRoute, useNavigation } from '@granite-js/react-native';

import { NutritionPanel } from '../../components/NutritionPanel';
import { RecipeDisplay } from '../../components/RecipeDisplay';
import { SearchForm } from '../../components/SearchForm';
import { useRecipeGenerate } from '../../hooks/useRecipeGenerate';

interface GenerateParams {
  dishName?: string;
  servings?: number;
}

export const Route = createRoute('/recipe/generate', {
  validateParams: (params: unknown): GenerateParams => {
    const obj = (params ?? {}) as Record<string, unknown>;
    return {
      dishName: typeof obj.dishName === 'string' ? obj.dishName : undefined,
      servings:
        typeof obj.servings === 'number'
          ? obj.servings
          : typeof obj.servings === 'string' && obj.servings.trim() !== ''
            ? Number(obj.servings)
            : undefined,
    };
  },
  component: GeneratePage,
});

function GeneratePage() {
  const params = Route.useParams();
  const navigation = useNavigation();
  // cancel()은 abort만 발사하고 status 전이가 비동기라 UI 일관성에 약함.
  // 본 화면은 취소 버튼·다시시도 모두 reset() 한 곳으로 통합한다.
  const { status, recipe, error, generate, reset } = useRecipeGenerate();

  // 초기 진입 자동 생성 — 1회만. params 변경 시 재실행하지 않는다(useRef 가드).
  const autoGeneratedRef = useRef(false);
  useEffect(() => {
    if (autoGeneratedRef.current) return;
    if (params.dishName && params.dishName.trim().length > 0) {
      autoGeneratedRef.current = true;
      void generate({
        dishName: params.dishName,
        servings: params.servings ?? 2,
        stream: true,
      });
    }
    // generate는 안정적인 함수지만 deps에 두지 않는다 — autoGeneratedRef 가드가 단일 트리거 보장.
  }, [params.dishName, params.servings, generate]);

  const handleManualSubmit = useCallback(
    (dishName: string, servings: number) => {
      reset();
      void generate({ dishName, servings, stream: true });
    },
    [generate, reset],
  );

  // 취소 버튼은 reset() 사용 — cancel()은 abort만 발사하고 status 전이는 비동기.
  // reset()은 동기 setState(status='idle')까지 보장하여 인디케이터가 즉시 사라진다 (AC2.2 UI 일관).
  const handleCancel = useCallback(() => {
    reset();
  }, [reset]);

  const handleRetry = useCallback(() => {
    const dishName = params.dishName?.trim();
    if (!dishName) {
      reset();
      return;
    }
    reset();
    void generate({ dishName, servings: params.servings ?? 2, stream: true });
  }, [params.dishName, params.servings, generate, reset]);

  const handleBackToHome = useCallback(() => {
    if (navigation.canGoBack?.()) {
      navigation.goBack();
    } else {
      navigation.navigate('/', {});
    }
  }, [navigation]);

  return (
    <View style={styles.root}>
      <PageNavbar>
        <PageNavbar.Title>레시피 생성</PageNavbar.Title>
      </PageNavbar>

      <ScrollView
        contentContainerStyle={styles.scrollContent}
        keyboardShouldPersistTaps="handled"
      >
        <SearchForm
          onSubmit={handleManualSubmit}
          initialDishName={params.dishName}
          initialServings={params.servings}
          pending={status === 'streaming'}
        />

        {status === 'streaming' ? (
          <View style={styles.indicator} accessibilityLabel="레시피 생성 진행 중">
            <Txt typography="t5" color="#191F28">
              AI가 레시피를 생성하고 있어요
            </Txt>
            <Txt typography="st9" color="#4E5968">
              몇 초 정도 걸릴 수 있어요. 잠시만 기다려 주세요.
            </Txt>
            <View style={styles.actions}>
              <Button
                type="light"
                style="weak"
                display="block"
                size="medium"
                onPress={handleCancel}
              >
                취소
              </Button>
            </View>
          </View>
        ) : null}

        {status === 'error' && error ? (
          <View style={styles.errorBox} accessibilityLabel="레시피 생성 실패">
            <Txt typography="t5" color="#C0392B">
              레시피 생성에 실패했어요
            </Txt>
            <Txt typography="st9" color="#4E5968">
              {error}
            </Txt>
            <View style={styles.actions}>
              <Button
                type="primary"
                style="fill"
                display="block"
                size="medium"
                onPress={handleRetry}
              >
                다시 시도
              </Button>
              <Button
                type="light"
                style="weak"
                display="block"
                size="medium"
                onPress={handleBackToHome}
              >
                홈으로
              </Button>
            </View>
          </View>
        ) : null}

        {status === 'done' && recipe ? (
          <View style={styles.result}>
            <RecipeDisplay recipe={recipe} />
            <NutritionPanel nutrition={recipe.nutrition} />
            {/* Phase 3 진입 시 저장 버튼이 actions slot으로 추가된다. */}
          </View>
        ) : null}

        {status === 'idle' && !params.dishName ? (
          <Txt typography="st9" color="#8B95A1">
            요리명과 인분을 입력하고 “레시피 만들기”를 눌러주세요.
          </Txt>
        ) : null}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    padding: 20,
    gap: 24,
  },
  indicator: {
    padding: 20,
    borderRadius: 12,
    backgroundColor: '#F2F4F6',
    gap: 8,
  },
  errorBox: {
    padding: 20,
    borderRadius: 12,
    backgroundColor: '#FBE9E9',
    gap: 8,
  },
  result: {
    gap: 24,
  },
  actions: {
    marginTop: 8,
    gap: 8,
  },
});
