/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _IndexRoute } from '../pages/';
import { Route as _RecipeGenerateRoute } from '../pages/recipe/generate';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/': (typeof _IndexRoute)['_inputType'];
    '/recipe/generate': (typeof _RecipeGenerateRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/': (typeof _IndexRoute)['_outputType'];
    '/recipe/generate': (typeof _RecipeGenerateRoute)['_outputType'];
  }
}
